#Offset is between -1:1
#z-location is between 0:1
---
poster:
  type: 'panel'
  number: 40
  type_specific:
    height: 1
    width: 0.7
    thickness: 0.02
    z_location: 0.8
    offset: 0
    wall: 'left'
    texture: 'Gazebo/Blue'
blocked_hole:
  type: 'blocked_hole'
  type_specific:
    dummy: ''
    wall: 'left'
    texture: 'Gazebo/OSB'
doorway:
  type: 'passway'
  number: 20
  type_specific:
    name: 'doorway'
    offset: 1
    texture: 'Gazebo/Grey'
ceiling:
  type: 'ceiling'
  type_specific:
    name: 'ceiling'
    dummy: ''
floor:
  type: 'floor'
  type_specific:
    name: 'floor'
    texture: 'Gazebo/Black'
