# PS3 wireless controller

#define PS3_BUTTON_SELECT            0
#define PS3_BUTTON_STICK_LEFT        1
#define PS3_BUTTON_STICK_RIGHT       2
#define PS3_BUTTON_START             3
#define PS3_BUTTON_CROSS_UP          4
#define PS3_BUTTON_CROSS_RIGHT       5
#define PS3_BUTTON_CROSS_DOWN        6
#define PS3_BUTTON_CROSS_LEFT        7
#define PS3_BUTTON_REAR_LEFT_2       8
#define PS3_BUTTON_REAR_RIGHT_2      9
#define PS3_BUTTON_REAR_LEFT_1       10
#define PS3_BUTTON_REAR_RIGHT_1      11
#define PS3_BUTTON_ACTION_TRIANGLE   12
#define PS3_BUTTON_ACTION_CIRCLE     13
#define PS3_BUTTON_ACTION_CROSS      14
#define PS3_BUTTON_ACTION_SQUARE     15
#define PS3_BUTTON_PAIRING           16

#define PS3_AXIS_STICK_LEFT_LEFTWARDS    0
#define PS3_AXIS_STICK_LEFT_UPWARDS      1
#define PS3_AXIS_STICK_RIGHT_LEFTWARDS   2
#define PS3_AXIS_STICK_RIGHT_UPWARDS     3
#define PS3_AXIS_BUTTON_CROSS_UP         4
#define PS3_AXIS_BUTTON_CROSS_RIGHT      5
#define PS3_AXIS_BUTTON_CROSS_DOWN       6
#define PS3_AXIS_BUTTON_CROSS_LEFT       7
#define PS3_AXIS_BUTTON_REAR_LEFT_2      8
#define PS3_AXIS_BUTTON_REAR_RIGHT_2     9
#define PS3_AXIS_BUTTON_REAR_LEFT_1      10
#define PS3_AXIS_BUTTON_REAR_RIGHT_1     11
#define PS3_AXIS_BUTTON_ACTION_TRIANGLE  12
#define PS3_AXIS_BUTTON_ACTION_CIRCLE    13
#define PS3_AXIS_BUTTON_ACTION_CROSS     14
#define PS3_AXIS_BUTTON_ACTION_SQUARE    15
#define PS3_AXIS_ACCELEROMETER_LEFT      16
#define PS3_AXIS_ACCELEROMETER_FORWARD   17
#define PS3_AXIS_ACCELEROMETER_UP        18
#define PS3_AXIS_GYRO_YAW                19

teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    #deadman_buttons: [7]
    axis_mappings:
      -
        axis: 3  # Right thumb stick (up/down)
        target: linear.x
        scale: 0.2
        offset: 0.0
      -
        axis: 2  # Right thumb stick (left/right)
        target: linear.y
        scale: 0.2
        offset: 0.0
      -
        axis: 1  # Left thumb stick (up/down)
        target: linear.z
        scale: 0.5
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 1.0
        offset: 0.0
  camera:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: camera_control
    deadman_buttons: [7]
    axis_mappings:
      -
        axis: 5  # Left D-Pad (up/down)
        target: angular.y
        scale: 35.0
        offset: 0.0
      -
        axis: 4  # Left D-Pad (left/right)
        target: angular.z
        scale: -35.0
        offset: 0.0
  takeoff:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: takeoff
    deadman_buttons: [2]  # start+up
    axis_mappings: []
  land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: land
    deadman_buttons: [1]  # start+down
    axis_mappings: []
  emergency:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: reset
    deadman_buttons: [11, 10] # left and right pointing finger
    axis_mappings: []
  flattrim:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: flattrim
    deadman_buttons: [0] # start+select
    axis_mappings: []
  flip:
    type: topic
    message_type: "std_msgs/UInt8"
    topic_name: flip
    deadman_buttons: [9,8,10,11] # 2middle fingers + circle
    axis_mappings: []
  snapshot:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: snapshot
    deadman_buttons: [8] # RT + LB
    axis_mappings: []
  overtake:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: overtake
    deadman_buttons: [14] #cross
    axis_mappings: []
  ready:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: ready
    deadman_buttons: [12] #Triangle
    axis_mappings: []
  rec_on:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: rec_on
    deadman_buttons: [15] #Square
    axis_mappings: []
  rec_off:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: rec_off
    deadman_buttons: [13] #Square
    axis_mappings: []

